mode: "dev"
port: 8081
version: "v0.0.1"
start_time: "2021-11-01"
mechine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "debug"
  filename: "./log/bluebell.log"
  max_size: 1000
  max_age: 3600
  max_backups: 5

mysql:
  host: 192.168.147.129
  port: 3306
  user: root
  password: root
  db: bluebell
  max_open_conns: 100
  max_idle_conns: 20

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0
  pool_size: 100